DjangoFinalProject/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('', include('taskManager.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

taskManager/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from taskManager import views

app_name = 'taskManager'
urlpatterns = [

    path('', views.TaskListView.as_view(), name='all-task'),
    path('task/create', views.TaskCreateView.as_view(), name='create-task'),
    path('task/<int:pk>', views.TaskDetailView.as_view(), name='detail-task'),
    path('task/update/<int:pk>', views.TaskUpdateView.as_view(), name='update-task'),
    path('task/delete/<int:pk>', views.TaskDeleteView.as_view(), name='delete-task'),

    path('api/task/', views.TaskList.as_view()),
    path('api/task/<int:pk>/', views.TaskDetail.as_view()),
    path('api/user/', views.UserList.as_view()),
    path('api/user/<int:pk>/', views.UserDetail.as_view()),

]

urlpatterns = format_suffix_patterns(urlpatterns)

taskManager/models.py
from django.core.validators import MinLengthValidator
from django.db import models


# Create your models here.
from django.conf import settings

STARTED_STATUS = 1
PROCESSING_STATUS = 2
PENDING_STATUS = 3
ENDED_STATUS = 4
STATUS_CHOICES = (
        (STARTED_STATUS, 'Started'),
        (PROCESSING_STATUS, 'Processing'),
        (PENDING_STATUS, 'Pending'),
        (ENDED_STATUS, 'Ended')
    )


class Task(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Task title must be greater than 1 character")]
    )
    description = models.CharField(
        max_length=2000,
        validators=[MinLengthValidator(2, "Project description must be greater than 1 character")]
    )

    status = models.IntegerField(choices=STATUS_CHOICES, default=STARTED_STATUS)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

taskManager/forms.py
from django import forms
from taskManager.models import Task


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'status']

taskManager/views.py
from datetime import time

from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.views.generic import DeleteView
from rest_framework import permissions, status, generics
from rest_framework.response import Response
from rest_framework.views import APIView

from taskManager.forms import CreateTaskForm
from taskManager.models import Task
from django.views import View

from taskManager.serializers import TaskSerializer, UserSerializer


class AuthorOrReadOnly(permissions.BasePermission):

    def has_permission(self, request, view):
        if request.user.is_authenticated:
            return True
        return False

    def has_object_permission(self, request, view, obj):
        if obj.owner == request.user:
            return True
        return False


class TaskListView(View):
    model = Task

    def get(self, request):
        strval = request.GET.get("search", False)
        if strval:
            query = Q(description__contains=strval) | Q(title__contains=strval)
            task_list = Task.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            task_list = Task.objects.all()
        ctx = {'task_list': task_list, 'search': strval}
        return render(request, "taskManager/task_list.html", ctx)


class TaskCreateView(LoginRequiredMixin, View):
    model = Task
    template_name = 'taskManager/task_form.html'

    def get(self, request, pk=None):
        form = CreateTaskForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateTaskForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        task = form.save(commit=False)
        task.owner = self.request.user
        task.save()
        return HttpResponseRedirect(reverse('taskManager:all-task'))


class TaskDetailView(View):
    model = Task

    def get(self, request, pk):
        x = get_object_or_404(Task, id=pk)
        ctx = {'task': x}
        return render(request, "taskManager/task_detail.html", ctx)


class TaskUpdateView(LoginRequiredMixin, View):
    model = Task
    template_name = 'taskManager/task_form.html'

    def get(self, request, pk=None):
        task = get_object_or_404(Task, id=pk, owner=request.user)
        form = CreateTaskForm(instance=task)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        task = get_object_or_404(Task, id=pk, owner=request.user)
        form = CreateTaskForm(request.POST, instance=task or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        task = form.save(commit=False)
        task.save()
        return HttpResponseRedirect(reverse('taskManager:all-task'))


# UserPassesTestMixin,
class TaskDeleteView(UserPassesTestMixin, DeleteView):
    model = Task
    raise_exception = True

    def test_func(self):
        self.object = self.get_object()
        return self.object.owner == self.request.user

    def get_success_url(self):
        return reverse('taskManager:all-task')


class TaskList(APIView):
    """
    List all code tasks, or create a new task.
    """
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def get(self, request, format=None):
        tasks = Task.objects.all()
        serializer = TaskSerializer(tasks, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = TaskSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(owner=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class TaskDetail(APIView):
    """
    Retrieve, update or delete a code task instance.
    """
    #permission_classes = [AuthorOrReadOnly]

    def get_object(self, pk):
        try:
            return Task.objects.get(pk=pk)
        except Task.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        self.permission_classes = [AuthorOrReadOnly]
        task = self.get_object(pk)
        serializer = TaskSerializer(task)
        return Response(serializer.data)

    def put(self, request, pk):
        self.permission_classes = [AuthorOrReadOnly]
        task = self.get_object(pk)
        serializer = TaskSerializer(task, data=request.data)
        if serializer.is_valid():
            serializer.save(owner=request.user)
            return Response(serializer.data)
        return Response(serializer.errors, status=400)

    def delete(self, request, pk):
        self.permission_classes = [AuthorOrReadOnly]
        task = self.get_object(pk)
        task.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class UserList(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

taskManager/templates/taskManager/task_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Task</h1>

<p>Are you sure you want to delete the Task: {{ task }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
 <input type="submit" value="Cancel" onclick="window.location.href='{% url 'taskManager:all-task' %}';return false;">
</form>
{% endblock %}

taskManager/templates/taskManager/task_detail.html
{% extends "base_bootstrap.html" %}
{% block content %}
    <h1>Title: {{ task.title }}</h1>
    <p>
        Task Description :
        {{ task.description }}
    </p>
    <p>
        Task Status :
        {{ task.get_status_display }}
    </p>

    <p>
        Task Owner :
        {{ task.owner }}
    </p>

    <a href="{% url 'taskManager:all-task'%}">BACK</a>


{% endblock %}

taskManager/templates/taskManager/task_form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>

  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
      <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'taskManager:all-task' %}';return false;">
  </form>
</p>

{% endblock %}

taskManager/templates/taskManager/task_list.html
{% extends "base_bootstrap.html" %}

{% block content %}

    <h1>Tasks</h1>
{% if task_list %}

    <div style="float:right">
            <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
            <form>
                <input type="text" placeholder="Search.." name="search"{% if search %} value="{{ search }}" {% endif %}>
                <button type="submit"><i class="fa fa-search"></i></button>
                <a href="{% url 'taskManager:all-task' %}"><i class="fa fa-undo"></i></a>
            </form>
        </div>


        <ul>
            {% for task in task_list %}

                <li>
                    <a href="{% url 'taskManager:detail-task' task.id%}" >{{ task.title }}</a>
                </li>
                {% if task.owner == user %}
                        (<a href="{% url 'taskManager:update-task' task.id%}">Edit</a> | <a href="{% url 'taskManager:delete-task' task.id%}">Delete</a>)
                {% endif %}


            {% endfor %}
        </ul>
    {% else %}
            <p>There are no tasks in the database.</p>
    {% endif %}

    <p>

    </p>

{% endblock %}

templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="42-42">

<meta name="dj4e-code" content="99999999">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2021-04-14">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

{% block head %} {% endblock %}

</head>
<body>

<!-- Navbar (sit on top) -->
<div>
  <div class="w3-bar w3-white w3-wide w3-padding w3-card">
    <a href="{% url 'taskManager:all-task' %}" class="w3-bar-item w3-button"><b>Task</b> Manager</a>
    <!-- Float links to the right. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
        {% if user.is_authenticated %}
            <a class="w3-bar-item w3-button" href="{% url 'taskManager:create-task' %}">Add New Task</a>
            <a class="w3-bar-item w3-button" href="{% url 'logout' %}?next={% url 'taskManager:all-task' %}">Logout</a>
        {% else %}
            <a class="w3-bar-item w3-button" href="{% url 'login' %}?next={% url 'taskManager:all-task' %}">Login</a>
        {% endif %}
    </div>
  </div>
</div>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>